-- Usuarios
INSERT INTO USUARIO (NOME_COMPLETO, USERNAME, EMAIL, SENHA) VALUES ('Guilherme Akira', 'gui', 'gui@email.com', 'senha123');
INSERT INTO USUARIO (NOME_COMPLETO, USERNAME, EMAIL, SENHA) VALUES ('Alice Nunes', 'alice', 'alice@email.com', 'abc12345');
INSERT INTO USUARIO (NOME_COMPLETO, USERNAME, EMAIL, SENHA) VALUES ('Anne Rezendes', 'anne', 'anne@email.com', 'anne321');
INSERT INTO USUARIO (NOME_COMPLETO, USERNAME, EMAIL, SENHA) VALUES ('João Menk', 'jmenk', 'jmenk@email.com', 'cloud123');
INSERT INTO USUARIO (NOME_COMPLETO, USERNAME, EMAIL, SENHA) VALUES ('Antonio', 'antonio', 'antonio@email.com', 'fiap');

-- Motos
INSERT INTO MOTOS (MODELO, PLACA, ANO, SETOR) VALUES ('MOTTU_E', 'ABC1D23', 2022, 'COM_PENDENCIA');
INSERT INTO MOTOS (MODELO, PLACA, ANO, SETOR) VALUES ('MOTTU_SPORT', 'EFG4H56', 2023, 'PRONTA_PARA_ALUGUEL');
INSERT INTO MOTOS (MODELO, PLACA, ANO, SETOR) VALUES ('MOTTU_POP', 'IJK7L89', 2021, 'MANUTENCAO');

-- IOTs (1:1 com moto)
INSERT INTO IOTS (MOTO_ID) VALUES (1);
INSERT INTO IOTS (MOTO_ID) VALUES (2);